// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace reflection
{

/// New schema language features that are not supported by old code generators.
[System.FlagsAttribute]
public enum AdvancedFeatures : ulong
{
  AdvancedArrayFeatures = 1,
  AdvancedUnionFeatures = 2,
  OptionalScalars = 4,
  DefaultVectorsAndStrings = 8,
};


}
