// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace reflection
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct EnumVal : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_24_3_25(); }
  public static EnumVal GetRootAsEnumVal(ByteBuffer _bb) { return GetRootAsEnumVal(_bb, new EnumVal()); }
  public static EnumVal GetRootAsEnumVal(ByteBuffer _bb, EnumVal obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public EnumVal __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public string Name { get { int o = __p.__offset(4); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetNameBytes() { return __p.__vector_as_span<byte>(4, 1); }
#else
  public ArraySegment<byte>? GetNameBytes() { return __p.__vector_as_arraysegment(4); }
#endif
  public byte[] GetNameArray() { return __p.__vector_as_array<byte>(4); }
  public long Value { get { int o = __p.__offset(6); return o != 0 ? __p.bb.GetLong(o + __p.bb_pos) : (long)0; } }
  public reflection.Type? UnionType { get { int o = __p.__offset(10); return o != 0 ? (reflection.Type?)(new reflection.Type()).__assign(__p.__indirect(o + __p.bb_pos), __p.bb) : null; } }
  public string Documentation(int j) { int o = __p.__offset(12); return o != 0 ? __p.__string(__p.__vector(o) + j * 4) : null; }
  public int DocumentationLength { get { int o = __p.__offset(12); return o != 0 ? __p.__vector_len(o) : 0; } }
  public reflection.KeyValue? Attributes(int j) { int o = __p.__offset(14); return o != 0 ? (reflection.KeyValue?)(new reflection.KeyValue()).__assign(__p.__indirect(__p.__vector(o) + j * 4), __p.bb) : null; }
  public int AttributesLength { get { int o = __p.__offset(14); return o != 0 ? __p.__vector_len(o) : 0; } }
  public reflection.KeyValue? AttributesByKey(string key) { int o = __p.__offset(14); return o != 0 ? reflection.KeyValue.__lookup_by_key(__p.__vector(o), key, __p.bb) : null; }

  public static Offset<reflection.EnumVal> CreateEnumVal(FlatBufferBuilder builder,
      StringOffset nameOffset = default(StringOffset),
      long value = 0,
      Offset<reflection.Type> union_typeOffset = default(Offset<reflection.Type>),
      VectorOffset documentationOffset = default(VectorOffset),
      VectorOffset attributesOffset = default(VectorOffset)) {
    builder.StartTable(6);
    EnumVal.AddValue(builder, value);
    EnumVal.AddAttributes(builder, attributesOffset);
    EnumVal.AddDocumentation(builder, documentationOffset);
    EnumVal.AddUnionType(builder, union_typeOffset);
    EnumVal.AddName(builder, nameOffset);
    return EnumVal.EndEnumVal(builder);
  }

  public static void StartEnumVal(FlatBufferBuilder builder) { builder.StartTable(6); }
  public static void AddName(FlatBufferBuilder builder, StringOffset nameOffset) { builder.AddOffset(0, nameOffset.Value, 0); }
  public static void AddValue(FlatBufferBuilder builder, long value) { builder.AddLong(1, value, 0); }
  public static void AddUnionType(FlatBufferBuilder builder, Offset<reflection.Type> unionTypeOffset) { builder.AddOffset(3, unionTypeOffset.Value, 0); }
  public static void AddDocumentation(FlatBufferBuilder builder, VectorOffset documentationOffset) { builder.AddOffset(4, documentationOffset.Value, 0); }
  public static VectorOffset CreateDocumentationVector(FlatBufferBuilder builder, StringOffset[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddOffset(data[i].Value); return builder.EndVector(); }
  public static VectorOffset CreateDocumentationVectorBlock(FlatBufferBuilder builder, StringOffset[] data) { builder.StartVector(4, data.Length, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateDocumentationVectorBlock(FlatBufferBuilder builder, ArraySegment<StringOffset> data) { builder.StartVector(4, data.Count, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateDocumentationVectorBlock(FlatBufferBuilder builder, IntPtr dataPtr, int sizeInBytes) { builder.StartVector(1, sizeInBytes, 1); builder.Add<StringOffset>(dataPtr, sizeInBytes); return builder.EndVector(); }
  public static void StartDocumentationVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
  public static void AddAttributes(FlatBufferBuilder builder, VectorOffset attributesOffset) { builder.AddOffset(5, attributesOffset.Value, 0); }
  public static VectorOffset CreateAttributesVector(FlatBufferBuilder builder, Offset<reflection.KeyValue>[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddOffset(data[i].Value); return builder.EndVector(); }
  public static VectorOffset CreateAttributesVectorBlock(FlatBufferBuilder builder, Offset<reflection.KeyValue>[] data) { builder.StartVector(4, data.Length, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateAttributesVectorBlock(FlatBufferBuilder builder, ArraySegment<Offset<reflection.KeyValue>> data) { builder.StartVector(4, data.Count, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateAttributesVectorBlock(FlatBufferBuilder builder, IntPtr dataPtr, int sizeInBytes) { builder.StartVector(1, sizeInBytes, 1); builder.Add<Offset<reflection.KeyValue>>(dataPtr, sizeInBytes); return builder.EndVector(); }
  public static void StartAttributesVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
  public static Offset<reflection.EnumVal> EndEnumVal(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    builder.Required(o, 4);  // name
    return new Offset<reflection.EnumVal>(o);
  }

  public static VectorOffset CreateSortedVectorOfEnumVal(FlatBufferBuilder builder, Offset<EnumVal>[] offsets) {
    Array.Sort(offsets,
      (Offset<EnumVal> o1, Offset<EnumVal> o2) =>
        new EnumVal().__assign(builder.DataBuffer.Length - o1.Value, builder.DataBuffer).Value.CompareTo(new EnumVal().__assign(builder.DataBuffer.Length - o2.Value, builder.DataBuffer).Value));
    return builder.CreateVectorOfTables(offsets);
  }

  public static EnumVal? __lookup_by_key(int vectorLocation, long key, ByteBuffer bb) {
    EnumVal obj_ = new EnumVal();
    int span = bb.GetInt(vectorLocation - 4);
    int start = 0;
    while (span != 0) {
      int middle = span / 2;
      int tableOffset = Table.__indirect(vectorLocation + 4 * (start + middle), bb);
      obj_.__assign(tableOffset, bb);
      int comp = obj_.Value.CompareTo(key);
      if (comp > 0) {
        span = middle;
      } else if (comp < 0) {
        middle++;
        start += middle;
        span -= middle;
      } else {
        return obj_;
      }
    }
    return null;
  }
  public EnumValT UnPack() {
    var _o = new EnumValT();
    this.UnPackTo(_o);
    return _o;
  }
  public void UnPackTo(EnumValT _o) {
    _o.Name = this.Name;
    _o.Value = this.Value;
    _o.UnionType = this.UnionType.HasValue ? this.UnionType.Value.UnPack() : null;
    _o.Documentation = new List<string>();
    for (var _j = 0; _j < this.DocumentationLength; ++_j) {_o.Documentation.Add(this.Documentation(_j));}
    _o.Attributes = new List<reflection.KeyValueT>();
    for (var _j = 0; _j < this.AttributesLength; ++_j) {_o.Attributes.Add(this.Attributes(_j).HasValue ? this.Attributes(_j).Value.UnPack() : null);}
  }
  public static Offset<reflection.EnumVal> Pack(FlatBufferBuilder builder, EnumValT _o) {
    if (_o == null) return default(Offset<reflection.EnumVal>);
    var _name = _o.Name == null ? default(StringOffset) : builder.CreateString(_o.Name);
    var _union_type = _o.UnionType == null ? default(Offset<reflection.Type>) : reflection.Type.Pack(builder, _o.UnionType);
    var _documentation = default(VectorOffset);
    if (_o.Documentation != null) {
      var __documentation = new StringOffset[_o.Documentation.Count];
      for (var _j = 0; _j < __documentation.Length; ++_j) { __documentation[_j] = builder.CreateString(_o.Documentation[_j]); }
      _documentation = CreateDocumentationVector(builder, __documentation);
    }
    var _attributes = default(VectorOffset);
    if (_o.Attributes != null) {
      var __attributes = new Offset<reflection.KeyValue>[_o.Attributes.Count];
      for (var _j = 0; _j < __attributes.Length; ++_j) { __attributes[_j] = reflection.KeyValue.Pack(builder, _o.Attributes[_j]); }
      _attributes = CreateAttributesVector(builder, __attributes);
    }
    return CreateEnumVal(
      builder,
      _name,
      _o.Value,
      _union_type,
      _documentation,
      _attributes);
  }
}

public class EnumValT
{
  public string Name { get; set; }
  public long Value { get; set; }
  public reflection.TypeT UnionType { get; set; }
  public List<string> Documentation { get; set; }
  public List<reflection.KeyValueT> Attributes { get; set; }

  public EnumValT() {
    this.Name = null;
    this.Value = 0;
    this.UnionType = null;
    this.Documentation = null;
    this.Attributes = null;
  }
}


static public class EnumValVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyString(tablePos, 4 /*Name*/, true)
      && verifier.VerifyField(tablePos, 6 /*Value*/, 8 /*long*/, 8, false)
      && verifier.VerifyTable(tablePos, 10 /*UnionType*/, reflection.TypeVerify.Verify, false)
      && verifier.VerifyVectorOfStrings(tablePos, 12 /*Documentation*/, false)
      && verifier.VerifyVectorOfTables(tablePos, 14 /*Attributes*/, reflection.KeyValueVerify.Verify, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}

}
