// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace reflection
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct Enum : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_24_3_25(); }
  public static Enum GetRootAsEnum(ByteBuffer _bb) { return GetRootAsEnum(_bb, new Enum()); }
  public static Enum GetRootAsEnum(ByteBuffer _bb, Enum obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public Enum __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public string Name { get { int o = __p.__offset(4); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetNameBytes() { return __p.__vector_as_span<byte>(4, 1); }
#else
  public ArraySegment<byte>? GetNameBytes() { return __p.__vector_as_arraysegment(4); }
#endif
  public byte[] GetNameArray() { return __p.__vector_as_array<byte>(4); }
  public reflection.EnumVal? Values(int j) { int o = __p.__offset(6); return o != 0 ? (reflection.EnumVal?)(new reflection.EnumVal()).__assign(__p.__indirect(__p.__vector(o) + j * 4), __p.bb) : null; }
  public int ValuesLength { get { int o = __p.__offset(6); return o != 0 ? __p.__vector_len(o) : 0; } }
  public reflection.EnumVal? ValuesByKey(long key) { int o = __p.__offset(6); return o != 0 ? reflection.EnumVal.__lookup_by_key(__p.__vector(o), key, __p.bb) : null; }
  public bool IsUnion { get { int o = __p.__offset(8); return o != 0 ? 0!=__p.bb.Get(o + __p.bb_pos) : (bool)false; } }
  public reflection.Type? UnderlyingType { get { int o = __p.__offset(10); return o != 0 ? (reflection.Type?)(new reflection.Type()).__assign(__p.__indirect(o + __p.bb_pos), __p.bb) : null; } }
  public reflection.KeyValue? Attributes(int j) { int o = __p.__offset(12); return o != 0 ? (reflection.KeyValue?)(new reflection.KeyValue()).__assign(__p.__indirect(__p.__vector(o) + j * 4), __p.bb) : null; }
  public int AttributesLength { get { int o = __p.__offset(12); return o != 0 ? __p.__vector_len(o) : 0; } }
  public reflection.KeyValue? AttributesByKey(string key) { int o = __p.__offset(12); return o != 0 ? reflection.KeyValue.__lookup_by_key(__p.__vector(o), key, __p.bb) : null; }
  public string Documentation(int j) { int o = __p.__offset(14); return o != 0 ? __p.__string(__p.__vector(o) + j * 4) : null; }
  public int DocumentationLength { get { int o = __p.__offset(14); return o != 0 ? __p.__vector_len(o) : 0; } }
  /// File that this Enum is declared in.
  public string DeclarationFile { get { int o = __p.__offset(16); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetDeclarationFileBytes() { return __p.__vector_as_span<byte>(16, 1); }
#else
  public ArraySegment<byte>? GetDeclarationFileBytes() { return __p.__vector_as_arraysegment(16); }
#endif
  public byte[] GetDeclarationFileArray() { return __p.__vector_as_array<byte>(16); }

  public static Offset<reflection.Enum> CreateEnum(FlatBufferBuilder builder,
      StringOffset nameOffset = default(StringOffset),
      VectorOffset valuesOffset = default(VectorOffset),
      bool is_union = false,
      Offset<reflection.Type> underlying_typeOffset = default(Offset<reflection.Type>),
      VectorOffset attributesOffset = default(VectorOffset),
      VectorOffset documentationOffset = default(VectorOffset),
      StringOffset declaration_fileOffset = default(StringOffset)) {
    builder.StartTable(7);
    Enum.AddDeclarationFile(builder, declaration_fileOffset);
    Enum.AddDocumentation(builder, documentationOffset);
    Enum.AddAttributes(builder, attributesOffset);
    Enum.AddUnderlyingType(builder, underlying_typeOffset);
    Enum.AddValues(builder, valuesOffset);
    Enum.AddName(builder, nameOffset);
    Enum.AddIsUnion(builder, is_union);
    return Enum.EndEnum(builder);
  }

  public static void StartEnum(FlatBufferBuilder builder) { builder.StartTable(7); }
  public static void AddName(FlatBufferBuilder builder, StringOffset nameOffset) { builder.AddOffset(0, nameOffset.Value, 0); }
  public static void AddValues(FlatBufferBuilder builder, VectorOffset valuesOffset) { builder.AddOffset(1, valuesOffset.Value, 0); }
  public static VectorOffset CreateValuesVector(FlatBufferBuilder builder, Offset<reflection.EnumVal>[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddOffset(data[i].Value); return builder.EndVector(); }
  public static VectorOffset CreateValuesVectorBlock(FlatBufferBuilder builder, Offset<reflection.EnumVal>[] data) { builder.StartVector(4, data.Length, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateValuesVectorBlock(FlatBufferBuilder builder, ArraySegment<Offset<reflection.EnumVal>> data) { builder.StartVector(4, data.Count, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateValuesVectorBlock(FlatBufferBuilder builder, IntPtr dataPtr, int sizeInBytes) { builder.StartVector(1, sizeInBytes, 1); builder.Add<Offset<reflection.EnumVal>>(dataPtr, sizeInBytes); return builder.EndVector(); }
  public static void StartValuesVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
  public static void AddIsUnion(FlatBufferBuilder builder, bool isUnion) { builder.AddBool(2, isUnion, false); }
  public static void AddUnderlyingType(FlatBufferBuilder builder, Offset<reflection.Type> underlyingTypeOffset) { builder.AddOffset(3, underlyingTypeOffset.Value, 0); }
  public static void AddAttributes(FlatBufferBuilder builder, VectorOffset attributesOffset) { builder.AddOffset(4, attributesOffset.Value, 0); }
  public static VectorOffset CreateAttributesVector(FlatBufferBuilder builder, Offset<reflection.KeyValue>[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddOffset(data[i].Value); return builder.EndVector(); }
  public static VectorOffset CreateAttributesVectorBlock(FlatBufferBuilder builder, Offset<reflection.KeyValue>[] data) { builder.StartVector(4, data.Length, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateAttributesVectorBlock(FlatBufferBuilder builder, ArraySegment<Offset<reflection.KeyValue>> data) { builder.StartVector(4, data.Count, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateAttributesVectorBlock(FlatBufferBuilder builder, IntPtr dataPtr, int sizeInBytes) { builder.StartVector(1, sizeInBytes, 1); builder.Add<Offset<reflection.KeyValue>>(dataPtr, sizeInBytes); return builder.EndVector(); }
  public static void StartAttributesVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
  public static void AddDocumentation(FlatBufferBuilder builder, VectorOffset documentationOffset) { builder.AddOffset(5, documentationOffset.Value, 0); }
  public static VectorOffset CreateDocumentationVector(FlatBufferBuilder builder, StringOffset[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddOffset(data[i].Value); return builder.EndVector(); }
  public static VectorOffset CreateDocumentationVectorBlock(FlatBufferBuilder builder, StringOffset[] data) { builder.StartVector(4, data.Length, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateDocumentationVectorBlock(FlatBufferBuilder builder, ArraySegment<StringOffset> data) { builder.StartVector(4, data.Count, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateDocumentationVectorBlock(FlatBufferBuilder builder, IntPtr dataPtr, int sizeInBytes) { builder.StartVector(1, sizeInBytes, 1); builder.Add<StringOffset>(dataPtr, sizeInBytes); return builder.EndVector(); }
  public static void StartDocumentationVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
  public static void AddDeclarationFile(FlatBufferBuilder builder, StringOffset declarationFileOffset) { builder.AddOffset(6, declarationFileOffset.Value, 0); }
  public static Offset<reflection.Enum> EndEnum(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    builder.Required(o, 4);  // name
    builder.Required(o, 6);  // values
    builder.Required(o, 10);  // underlying_type
    return new Offset<reflection.Enum>(o);
  }

  public static VectorOffset CreateSortedVectorOfEnum(FlatBufferBuilder builder, Offset<Enum>[] offsets) {
    Array.Sort(offsets,
      (Offset<Enum> o1, Offset<Enum> o2) =>
        new Enum().__assign(builder.DataBuffer.Length - o1.Value, builder.DataBuffer).Name.CompareTo(new Enum().__assign(builder.DataBuffer.Length - o2.Value, builder.DataBuffer).Name));
    return builder.CreateVectorOfTables(offsets);
  }

  public static Enum? __lookup_by_key(int vectorLocation, string key, ByteBuffer bb) {
    Enum obj_ = new Enum();
    int span = bb.GetInt(vectorLocation - 4);
    int start = 0;
    while (span != 0) {
      int middle = span / 2;
      int tableOffset = Table.__indirect(vectorLocation + 4 * (start + middle), bb);
      obj_.__assign(tableOffset, bb);
      int comp = obj_.Name.CompareTo(key);
      if (comp > 0) {
        span = middle;
      } else if (comp < 0) {
        middle++;
        start += middle;
        span -= middle;
      } else {
        return obj_;
      }
    }
    return null;
  }
  public EnumT UnPack() {
    var _o = new EnumT();
    this.UnPackTo(_o);
    return _o;
  }
  public void UnPackTo(EnumT _o) {
    _o.Name = this.Name;
    _o.Values = new List<reflection.EnumValT>();
    for (var _j = 0; _j < this.ValuesLength; ++_j) {_o.Values.Add(this.Values(_j).HasValue ? this.Values(_j).Value.UnPack() : null);}
    _o.IsUnion = this.IsUnion;
    _o.UnderlyingType = this.UnderlyingType.HasValue ? this.UnderlyingType.Value.UnPack() : null;
    _o.Attributes = new List<reflection.KeyValueT>();
    for (var _j = 0; _j < this.AttributesLength; ++_j) {_o.Attributes.Add(this.Attributes(_j).HasValue ? this.Attributes(_j).Value.UnPack() : null);}
    _o.Documentation = new List<string>();
    for (var _j = 0; _j < this.DocumentationLength; ++_j) {_o.Documentation.Add(this.Documentation(_j));}
    _o.DeclarationFile = this.DeclarationFile;
  }
  public static Offset<reflection.Enum> Pack(FlatBufferBuilder builder, EnumT _o) {
    if (_o == null) return default(Offset<reflection.Enum>);
    var _name = _o.Name == null ? default(StringOffset) : builder.CreateString(_o.Name);
    var _values = default(VectorOffset);
    if (_o.Values != null) {
      var __values = new Offset<reflection.EnumVal>[_o.Values.Count];
      for (var _j = 0; _j < __values.Length; ++_j) { __values[_j] = reflection.EnumVal.Pack(builder, _o.Values[_j]); }
      _values = CreateValuesVector(builder, __values);
    }
    var _underlying_type = _o.UnderlyingType == null ? default(Offset<reflection.Type>) : reflection.Type.Pack(builder, _o.UnderlyingType);
    var _attributes = default(VectorOffset);
    if (_o.Attributes != null) {
      var __attributes = new Offset<reflection.KeyValue>[_o.Attributes.Count];
      for (var _j = 0; _j < __attributes.Length; ++_j) { __attributes[_j] = reflection.KeyValue.Pack(builder, _o.Attributes[_j]); }
      _attributes = CreateAttributesVector(builder, __attributes);
    }
    var _documentation = default(VectorOffset);
    if (_o.Documentation != null) {
      var __documentation = new StringOffset[_o.Documentation.Count];
      for (var _j = 0; _j < __documentation.Length; ++_j) { __documentation[_j] = builder.CreateString(_o.Documentation[_j]); }
      _documentation = CreateDocumentationVector(builder, __documentation);
    }
    var _declaration_file = _o.DeclarationFile == null ? default(StringOffset) : builder.CreateString(_o.DeclarationFile);
    return CreateEnum(
      builder,
      _name,
      _values,
      _o.IsUnion,
      _underlying_type,
      _attributes,
      _documentation,
      _declaration_file);
  }
}

public class EnumT
{
  public string Name { get; set; }
  public List<reflection.EnumValT> Values { get; set; }
  public bool IsUnion { get; set; }
  public reflection.TypeT UnderlyingType { get; set; }
  public List<reflection.KeyValueT> Attributes { get; set; }
  public List<string> Documentation { get; set; }
  public string DeclarationFile { get; set; }

  public EnumT() {
    this.Name = null;
    this.Values = null;
    this.IsUnion = false;
    this.UnderlyingType = null;
    this.Attributes = null;
    this.Documentation = null;
    this.DeclarationFile = null;
  }
}


static public class EnumVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyString(tablePos, 4 /*Name*/, true)
      && verifier.VerifyVectorOfTables(tablePos, 6 /*Values*/, reflection.EnumValVerify.Verify, true)
      && verifier.VerifyField(tablePos, 8 /*IsUnion*/, 1 /*bool*/, 1, false)
      && verifier.VerifyTable(tablePos, 10 /*UnderlyingType*/, reflection.TypeVerify.Verify, true)
      && verifier.VerifyVectorOfTables(tablePos, 12 /*Attributes*/, reflection.KeyValueVerify.Verify, false)
      && verifier.VerifyVectorOfStrings(tablePos, 14 /*Documentation*/, false)
      && verifier.VerifyString(tablePos, 16 /*DeclarationFile*/, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}

}
