name: Build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    strategy:
      matrix:
        configuration: [Release]
        rid: [win-x64, linux-x64, osx-x64]

    runs-on: windows-latest  # For a list of available runner types, refer to
                             # https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idruns-on

    env:
      Solution_Name: MemoryPack2Json.sln

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    # Install the .NET Core workload
    - name: Install .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    # Execute all unit tests in the solution
    - name: Execute unit tests
      run: dotnet test

    # Package the application
    - name: Package the application
      run: dotnet publish -c $env:Configuration -r $env:rid
      env:
        Configuration: ${{ matrix.configuration }}
        rid: ${{ matrix.rid }}

    # Upload the package: https://github.com/marketplace/actions/upload-a-build-artifact
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: MemoryPack2Json-${{ matrix.configuration }}-{{ matrix.rid }}
        path: bin\${{ matrix.configuration }}\net8.0\{{ matrix.rid }}\publish
